### ISSUE TITLE
Doesn't handle circular references

### ISSUE THREAD

**Issue by robross0606** [blackflux/object-treeify#1055]
If the object passed to this routine has circular references, the library loops indefinitely until running out of memory.

**Comment by simlu** [comment]
Hello and thanks for the ticket!

You are correct and it seems that [treeify](https://github.com/notatestuser/treeify/blob/master/treeify.js#L65) does handle this case.

I'll take a look. It should be an easy change.

**Comment by robross0606** [comment]
Even if you do a bugfix, 3.x has migrated to ESM which we cannot support at the moment, so I'm stuck on 2.x

**Comment by simlu** [comment]
I'll see if I can backmerge the fix.

A lot of libraries are moving to ESM. So sooner or later you will need to support it unfortunately.

You might be able to use treeify in the meantime?

**Comment by simlu** [comment]
Fix is done here: https://github.com/blackflux/object-treeify/pull/1056

Let me take a look at the backmerge

**Comment by simlu** [comment]
Backported to `2.1.1`

Change commit for that version can be found [here](https://github.com/blackflux/object-treeify/commit/4627b890baa23dfcf80bf455a040b99917815267).

Closing this since the original concern is addressed.

Please don't hesitate to comment here or open a new ticket if you have any questions
